#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

runApplication blockMesh

# runApplication surfaceConvert -scale 1 constant/geometry/surfacemesh_ref.stl constant/geometry/surfacemesh.stl
runApplication surfaceTransformPoints "scale=(0.05 0.05 0.05), translate=(0.2 0.5 0)" constant/geometry/surfacemesh_ref.stl constant/geometry/surfacemesh.stl

runApplication surfaceFeatures

runApplication snappyHexMesh

runApplication extrudeMesh

runApplication createPatch

runApplication checkMesh -latestTime

runApplication transformPoints "translate=(0 0 0.05), scale=(1 1 0.1)"

runApplication foamRun

# runApplication foamPostProcess -latestTime -func "mag(U)"

# runApplication -s cutPlane foamPostProcess -latestTime -func cutPlane

# ----------------------------------------------------------------- end-of-file
