#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

SCRIPT_DIR_NAME="$(basename $(pwd))"
touch "$SCRIPT_DIR_NAME".foam""

runApplication gmshToFoam FreeCAD_GMSH/reactor_tube.msh

runApplication transformPoints "scale=(1e-2 1e-2 1e-2), Rx=90"

runApplication createPatch -dict system/createPatchDict.1 # -overwrite

## Parallel
runApplication decomposePar

runParallel foamRun

# runApplication reconstructPar

#------------------------------------------------------------------------------
