#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

SCRIPT_DIR_NAME="$(basename $(pwd))"
touch "$SCRIPT_DIR_NAME".foam""

# runApplication surfaceAutoPatch constant/geometry/tube_grib_closed.stl constant/geometry/tube_grib_closed_out.stl 130

runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh
runApplication createPatch

runApplication transformPoints "translate=(0 0 -0.04)"

## Parallel
runApplication decomposePar

runParallel foamRun

# runApplication reconstructPar

#------------------------------------------------------------------------------
