#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication chemkinToFoam \
               chemkin/chem_h2air.inp chemkin/thermo_h2air.dat chemkin/transportProperties \
               constant/reactions constant/thermo
#------------------------------------------------------------------------------
