#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

# cp -r 0.reflecting 0/
cp -r 0.non-reflecting 0/

./Allpre

./Allmesh

runApplication foamRun

# ----------------------------------------------------------------- end-of-file
