#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

[ -d "0/" ] && rm -r "0/"

cleanCase

#------------------------------------------------------------------------------
