#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

SCRIPT_DIR_NAME="$(basename $(pwd))"
touch "$SCRIPT_DIR_NAME".foam""

runApplication blockMesh

runApplication surfaceConvert -scale 0.01 constant/geometry/surfacemesh_ref.stl constant/geometry/surfacemesh.stl

runApplication surfaceFeatures

runApplication snappyHexMesh

runApplication extrudeMesh

runApplication createPatch

runApplication checkMesh -latestTime

# runApplication transformPoints "scale=(0.1 0.1 0.1)"

## Parallel
runApplication decomposePar

runParallel foamRun

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
